version: 2.1
jobs:
  lint:
    docker:
      - image: euantorano/zig:0.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run linter
          command: |
            zig fmt --check src/main.zig
  test_latest:
    docker:
      - image: euantorano/zig:0.8.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: print zig version
          command: |
            zig version
      - run:
          name: run tests
          command: |
            zig build test
workflows:
  version: 2
  commit:
    jobs:
      - test_latest
      - lint
