name: Lint and test

on:
  push:
    branches: [ main ]
  pull_request:    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Build
      run: git submodule update --init --recursive && zig build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Lint
      run: zig fmt --check src/*.zig

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Test
      run: git submodule update --init --recursive && zig build test

  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.11.0
    
      - name: Test
        run: git submodule update --init --recursive && zig build -Dtarget="aarch64-linux"
