name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.12.0

    - name: Build
      run: git submodule update --init --recursive && zig build

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: master

    - name: Lint
      run: zig fmt --check src/*.zig

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.12.0

    - name: Test
      run: git submodule update --init --recursive && zig build test

  build-aarch64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.12.0
    
      - name: Check for presence of qemu-aarch64
        run: |
          if [[ `which qemu-aarch64` != '' ]]; then
            echo "HAS_QEMU_AARCH64=true" >> "$GITHUB_ENV"
          else 
            echo "HAS_QEMU_AARCH64=false" >> "$GITHUB_ENV"
          fi
      
      - name: Get submodules
        run: git submodule update --init --recursive
        
      - name: Build
        run: zig build -Dtarget="aarch64-linux"
        
      - name: Test
        if: env.HAS_QEMU_AARCH64 == 'true'
        run: zig build test -Dtarget="aarch64-linux"

  build-riscv64:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.12.0
    
      - name: Check for presence of qemu-riscv64
        run: |
          if [[ `which qemu-riscv64` != '' ]]; then
            echo "HAS_QEMU_RISCV64=true" >> "$GITHUB_ENV"
          else 
            echo "HAS_QEMU_RISCV64=false" >> "$GITHUB_ENV"
          fi
      
      - name: Get submodules
        run: git submodule update --init --recursive
        
      - name: Build
        run:  zig build -Dtarget="riscv64-linux"

      - name: Test
        if: env.HAS_QEMU_RISCV64 == 'true'
        run:  zig build test -Dtarget="riscv64-linux"
